package:
  name: eurec4a_snd
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - setuptools-git-version
  run:
    - python
    - numpy
    - matplotlib
    - basemap
    - netCDF4
    - pillow
    - eccodes
    - metpy
    - basemap-data-hires
    - tqdm
